<a href="https://colab.research.google.com/github/Prajwal-ak-0/machine-learning-1/blob/main/Part_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Introduction to Machine Learning and Deep Learning

**Machine Learning (ML)**: A branch of AI that learns from data and predicts unseen data. It can be applied everywhere, as long as we are able to convert the data into numbers, program it, and find patterns.

### Differences between ML and DL
* **Machine Learning (ML)** is generally applied to structured data.
* **Deep Learning (DL)**, a subset of ML, is typically applied to unstructured data.

### When to Apply ML/DL
* When we cannot specify all the rules we are going to encounter and the environment keeps changing with time.
* When there is a large amount of data, we can use ML/DL to gain insights.

### When Not to Apply DL
* If we can solve the problem with simple ML, it is better to avoid DL as it requires more computation.
* In the absence of large data, ML is preferred to deliver accurate results.

![Machine Learning vs Deep Learning](https://assets-global.website-files.com/5fb24a974499e90dae242d98/60f6fcbbeb0b8f57a7980a98_5f213db7c7763a9288759ad1_5eac2d0ef117c236e34cc0ff_DeepLearning.jpeg)

# Artificial Neural Network (ANN)

**Artificial Neural Network (ANN)**: A model inspired by the structure and function of biological neural networks. It consists of:

1. **Input Layer**: The incoming data is fed into this layer. Generally, it is a single layer.
2. **Hidden Layer(s)**: The model can consist of any number of hidden layers. Each layer helps in feature extraction.
3. **Output Layer**: Based on the extracted features, this layer makes the final decision.




# 2. Tensorflow basics

**TensorFlow**: An end-to-end open-source machine learning platform used to develop models for various tasks, including natural language processing, image recognition, etc.

* Contains prebuilt models.
* Provides the tools to build or customize a model.


In [4]:
import tensorflow as tf

In [5]:
scalar = tf.constant(10)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [6]:
vector = tf.constant([10,20,30,40])
vector

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([10, 20, 30, 40], dtype=int32)>

In [12]:
matrix = tf.constant([[10,20,30,40], [40,50,60,80]])
matrix

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[10, 20, 30, 40],
       [40, 50, 60, 80]], dtype=int32)>

In [15]:
tensor = tf.constant([[[10,20,30],[40,50,60]], [[10,20,30],[40,50,60]], [[10,20,30],[40,50,60]], [[10,20,30],[40,50,60]]])
tensor

<tf.Tensor: shape=(4, 2, 3), dtype=int32, numpy=
array([[[10, 20, 30],
        [40, 50, 60]],

       [[10, 20, 30],
        [40, 50, 60]],

       [[10, 20, 30],
        [40, 50, 60]],

       [[10, 20, 30],
        [40, 50, 60]]], dtype=int32)>